### ISSUE TITLE
This app doesn't work on KitKat

### ISSUE THREAD

**Issue by TheComputerGuy96** [topjohnwu/MagiskManager#26]
@topjohnwu or somebody else, make this app compatible with Android API 19! 😠

(Note: I've tried to install Magisk v8 with some hacks and it worked (including Magisk's PHH Superuser (also with some hacks)

**Comment by TheComputerGuy96** [comment]
@topjohnwu, please tell me why you can't make this app working on KitKat?

**Comment by topjohnwu** [comment]
Because the official Magisk does not support any Android version lower than 5.0
I used many features in the app that is not supported below 5.0, it would take time to add compatibility support for the app.
Personally, I don't have any device running below 5.0. The selinux and binaries (toolbox/toybox etc.) is also largely different from 4.4 to 5.0. It will be a pain for me to support the legacy devices.
Any developer is free to add unofficial KitKat support for Magisk.

**Comment by TheComputerGuy96** [comment]
@topjohnwu OK, I understand that it's hard to make Magisk supported on KitKat
Note: I've got Magisk (but not Magisk Manager) and Magisk's PHH Superuser working on KitKat:
[[http://i.imgur.com/Ka3W1vv.jpg|alt=Magisk v8 on KitKat]]

**Comment by TheComputerGuy96** [comment]
Here's a image of the Magisk logcat:
[[http://i.imgur.com/Ka3W1vv.jpg|alt=Magisk]]

**Comment by TheComputerGuy96** [comment]
![Magisk](http://i.imgur.com/Ka3W1vv.jpg)
