### ISSUE TITLE
Modules do not install on Moto G2 XT1078 (6.0.1)

### ISSUE THREAD

**Issue by ranit8** [topjohnwu/MagiskManager#262]
Magisk 13.3 installs successfully via recovery, and it gives me root.

After installing any module through Magisk Manager,the installation appears successful. But after rebooting, the module has that message in red, "Module will be updated at next reboot", and it never is.

Can't reinstall Magisk 13.3 from Manager, it fails. Uninstalled and installed from recovery, it had no effect.

I tried installing 3 modules via recovery, and all of them are installed properly as the programs run from an adb shell. But 2 of these, which I attempted to install before from Magisk Manager, still have that red message. The other one, which I installed only via recovery, is on the list as well, but it has no such message.
![screenshot_20170811-230023](https://user-images.githubusercontent.com/9259786/29236888-13ef9e12-7ee9-11e7-9a06-f0ebbe6b6a75.png)

**Comment by Didgeridoohan** [comment]
Remove the "update" file from the module folders in /magisk.

This is caused by a bug in v13.3 and module template v4, where you on some devices have to install modules in recovery. It's been fixed and installing modules through the Manager should work in v13.5 beta and on.

If you could try v13.5 beta and confirm it's been fixed that would be great.

**Comment by ranit8** [comment]
I have been offline for a while, didn't try v13.5 beta. But v14.0 has solved the problem. I'll close the issue.
