### ISSUE TITLE
App crashes on lunch

### ISSUE THREAD

**Issue by KirosC** [topjohnwu/MagiskManager#46]
I tried unroot, SuperSu, phh but every time I start the app it crashed. It asked for root permission before it crashed.

Device: Oneplus One
Rom: Unofficial TEMASEK  11.7 Uber

**Comment by Addrar** [comment]
Just don't open the app at lunch

**Comment by tonymanou** [comment]
@KirosC could you try to capture a portion of your logcat where we could see the exception that makes MagiskManager crash?

**Comment by KirosC** [comment]
[http://pastebin.com/raw/HF3DAkT8](url)

**Comment by tonymanou** [comment]
You error seems related to ProGuard (missing static constructor in class), but it's weird you are the only one complaining about this issue because this affects compiled code...
Which version of MagiskManager are you using?

**Side note:** I see that the Google Play Services client inside MagiskManager complains about ```com.google.android.gms``` signature being invalid, are you using microG project? =)

**Comment by JERW86** [comment]
I had this issue too. Magisk Manager 3.0 crashed for me as well and I am using microG 0.2.4-39 (the latest build). Its crashing because the app is not finding SafetyNet within mircoG. 

This is solved by Installing the latest version of droidgaurd helper, which spoofs the exsistance of SN, from the microG F-droid repository. After installing the helper apk, Magisk Manager will open as usual.

**Comment by KirosC** [comment]
I'm not using microG. This is the first time I heard it. Will reinstall google play service solve the problem?

**Comment by JERW86** [comment]
I'm not familiar with your device or rom but before you try to reinstall play services, I suggest making sure all permissions are grated to the app. I think there is only one. If that doesn't work then you can reinstall the latest play services and see if that helps. 
If all else fails, start from a clean install of your Rom and reflash Magisk and the manager apk.

Good luck!

**Comment by topjohnwu** [comment]
This should fix it bb2467d2ac7ca29cf9970ed82e4ce66ec858f5be
Also, I changed to manual check SN here 442fcf921c11ebba4eae268cc026a902fdd20383
