### ISSUE TITLE
can't use root toggle button

### ISSUE THREAD

**Issue by kevlarcade** [topjohnwu/MagiskManager#7]
I'm on a CM13 and I full unroot using supersu then I flash Magisk V6 then SuperSu for Magisk and on reboot I install Magisk manager apk's. But when I try to turn off "toggle root" button, it immediatly turn back on.
Using oneplus one with CM13 marshmallow from official cyanogen website.

**Comment by paulschmeida** [comment]
Do you have SuperSU app in your system? I've had the same problem with phh's superuser, because there was no application to actually show a root request monit for you to accept. Magisk Manager needs root to work. So my guess is just install SuperSU from Play Store, then allow Magisk Manager to use root permissions.

**Comment by topjohnwu** [comment]
This release, and all future versions won't have root toggle

**Comment by zdenekhorak** [comment]
In another words - Magisk just became useless.
